// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlumbingBiddingTool.Infrastructure.Data;

#nullable disable

namespace PlumbingBiddingTool.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209035244_AddItemTypeToBidItem")]
    partial class AddItemTypeToBidItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BidItemFixtureItem", b =>
                {
                    b.Property<int>("BidItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixtureItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BidItemsId", "FixtureItemId");

                    b.HasIndex("FixtureItemId");

                    b.ToTable("FixtureItemBidItems", (string)null);
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.BidItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BidItems");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.FixtureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FixtureItems");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.JobFixtureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixtureItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FixtureItemId");

                    b.HasIndex("JobId");

                    b.ToTable("JobFixtureItems");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.JobOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobOptions");
                });

            modelBuilder.Entity("BidItemFixtureItem", b =>
                {
                    b.HasOne("PlumbingBiddingTool.Domain.Entities.BidItem", null)
                        .WithMany()
                        .HasForeignKey("BidItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbingBiddingTool.Domain.Entities.FixtureItem", null)
                        .WithMany()
                        .HasForeignKey("FixtureItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.Job", b =>
                {
                    b.HasOne("PlumbingBiddingTool.Domain.Entities.Contractor", "Contractor")
                        .WithMany("Jobs")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.JobFixtureItem", b =>
                {
                    b.HasOne("PlumbingBiddingTool.Domain.Entities.FixtureItem", "FixtureItem")
                        .WithMany()
                        .HasForeignKey("FixtureItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlumbingBiddingTool.Domain.Entities.Job", "Job")
                        .WithMany("JobFixtureItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixtureItem");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.JobOption", b =>
                {
                    b.HasOne("PlumbingBiddingTool.Domain.Entities.Job", "Job")
                        .WithMany("JobOptions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.Contractor", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.Job", b =>
                {
                    b.Navigation("JobFixtureItems");

                    b.Navigation("JobOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
