// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlumbingBiddingTool.Infrastructure.Data;

#nullable disable

namespace PlumbingBiddingTool.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BidItemFixtureItem", b =>
                {
                    b.Property<int>("BidItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixtureItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BidItemsId", "FixtureItemId");

                    b.HasIndex("FixtureItemId");

                    b.ToTable("FixtureItemBidItems", (string)null);
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.BidItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BidItems");
                });

            modelBuilder.Entity("PlumbingBiddingTool.Domain.Entities.FixtureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FixtureItems");
                });

            modelBuilder.Entity("BidItemFixtureItem", b =>
                {
                    b.HasOne("PlumbingBiddingTool.Domain.Entities.BidItem", null)
                        .WithMany()
                        .HasForeignKey("BidItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbingBiddingTool.Domain.Entities.FixtureItem", null)
                        .WithMany()
                        .HasForeignKey("FixtureItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
